import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme-provider";
import { Sidebar } from "@/components/sidebar/sidebar";
import { Sora } from "next/font/google";
import { ModalProvider } from "@/provider/modal-provider";

const typeface = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce-Appgit ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-screen w-full flex ${typeface.className} antialiased`}
      >
        <ModalProvider/>
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
        >
          <div className="h-full w-[80px]">
            <Sidebar/>
          </div>
          <div className="h-full flex-grow overflow-hidden overflow-y-scroll">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
